---
name: Windows

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python 3.10 on Windows
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run release
        uses: python-semantic-release/python-semantic-release@main
        with:
          root_options: -vv
          github_token: ${{ secrets.GITHUB_TOKEN }}
